### ISSUE TITLE
Not able to install with npm

### ISSUE THREAD

**Issue by dlmr** [prometheusresearch/zuul-builder-webpack#1]
I understand that this is still under development but I wanted to try it out but it would not let me install it using npm. When trying to install it requested me to enter authentication details for Github.

This might be a problem on my side, I'm not sure.

**Comment by andreypopp** [comment]
It will be released on npm soon, when https://github.com/defunctzombie/zuul/pull/190 is merged.

**Comment by dlmr** [comment]
I understand.

However I followed the "guide" in the README.md and when trying to install directly from Github as stated it did not work, e.g:

`npm install prometheusresearch/zuul-webpack-builder`

Maybe it is not supposed to work, just wanted to give a heads up. :)

On another note. I'm trying to make it work with my tests but I'm having some slight problems at the moment. An example would be awesome in the future, when you have time of course.

**Comment by andreypopp** [comment]
@DLMR not sure why this doesn't work, maybe some npm glitch or I don't know. It works for me fine though. You can try cloning the repo and do `npm install ./repo` if you want to try it now.

**Comment by dlmr** [comment]
I created a temporary fork and installed it that way for now, thanks for the quick reply!
