### ISSUE TITLE
does this supports `watch`?

### ISSUE THREAD

**Issue by vvo** [prometheusresearch/zuul-builder-webpack#3]
Let's say I use this zuul builder webpack, when in zuul --dev mode, modifying one file, will it update my webpack bundle when I refresh the zuul page?

Does it uses some cache? (like the default zuul watchify builder)

thanks

**Comment by andreypopp** [comment]
Not sure about `--dev`, I thought this is about zuul's bundle, not test code. But this builder watches for changes and caches, yes.

**Comment by vvo** [comment]
Thanks
